/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _i1;
import 'package:serverpod_client/serverpod_client.dart' as _i2;
import 'dart:async' as _i3;
import 'package:backend_client/src/protocol/greetings/greeting.dart' as _i4;
import 'package:backend_client/src/protocol/history/workout_record_dto.dart'
    as _i5;
import 'package:backend_client/src/protocol/schedule/training_schedule_dto.dart'
    as _i6;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i7;
import 'protocol.dart' as _i8;

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _i1.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _i3.Future<_i1.AuthSuccess> refreshAccessToken({
    required String refreshToken,
  }) => caller.callServerEndpoint<_i1.AuthSuccess>(
    'jwtRefresh',
    'refreshAccessToken',
    {'refreshToken': refreshToken},
    authenticated: false,
  );
}

/// {@category Endpoint}
class EndpointTelegramAuth extends _i2.EndpointRef {
  EndpointTelegramAuth(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'telegramAuth';

  _i3.Future<_i1.AuthSuccess> authenticate(String initData) =>
      caller.callServerEndpoint<_i1.AuthSuccess>(
        'telegramAuth',
        'authenticate',
        {'initData': initData},
      );
}

/// This is an example endpoint that returns a greeting message through
/// its [hello] method.
/// {@category Endpoint}
class EndpointGreeting extends _i2.EndpointRef {
  EndpointGreeting(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'greeting';

  /// Returns a personalized greeting message: "Hello {name}".
  _i3.Future<_i4.Greeting> hello(String name) =>
      caller.callServerEndpoint<_i4.Greeting>(
        'greeting',
        'hello',
        {'name': name},
      );
}

/// {@category Endpoint}
class EndpointWorkoutHistory extends _i2.EndpointRef {
  EndpointWorkoutHistory(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'workoutHistory';

  _i3.Future<List<_i5.WorkoutRecordDto>> list() =>
      caller.callServerEndpoint<List<_i5.WorkoutRecordDto>>(
        'workoutHistory',
        'list',
        {},
      );

  _i3.Future<_i5.WorkoutRecordDto> save(_i5.WorkoutRecordDto record) =>
      caller.callServerEndpoint<_i5.WorkoutRecordDto>(
        'workoutHistory',
        'save',
        {'record': record},
      );
}

/// {@category Endpoint}
class EndpointTrainingSchedule extends _i2.EndpointRef {
  EndpointTrainingSchedule(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'trainingSchedule';

  _i3.Future<_i6.TrainingScheduleDto?> get() =>
      caller.callServerEndpoint<_i6.TrainingScheduleDto?>(
        'trainingSchedule',
        'get',
        {},
      );

  _i3.Future<_i6.TrainingScheduleDto> save(_i6.TrainingScheduleDto schedule) =>
      caller.callServerEndpoint<_i6.TrainingScheduleDto>(
        'trainingSchedule',
        'save',
        {'schedule': schedule},
      );

  _i3.Future<void> delete() => caller.callServerEndpoint<void>(
    'trainingSchedule',
    'delete',
    {},
  );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_core = _i1.Caller(client);
    serverpod_auth_idp = _i7.Caller(client);
  }

  late final _i1.Caller serverpod_auth_core;

  late final _i7.Caller serverpod_auth_idp;
}

class Client extends _i2.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    @Deprecated(
      'Use authKeyProvider instead. This will be removed in future releases.',
    )
    super.authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i2.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_i2.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
         host,
         _i8.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
       ) {
    jwtRefresh = EndpointJwtRefresh(this);
    telegramAuth = EndpointTelegramAuth(this);
    greeting = EndpointGreeting(this);
    workoutHistory = EndpointWorkoutHistory(this);
    trainingSchedule = EndpointTrainingSchedule(this);
    modules = Modules(this);
  }

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointTelegramAuth telegramAuth;

  late final EndpointGreeting greeting;

  late final EndpointWorkoutHistory workoutHistory;

  late final EndpointTrainingSchedule trainingSchedule;

  late final Modules modules;

  @override
  Map<String, _i2.EndpointRef> get endpointRefLookup => {
    'jwtRefresh': jwtRefresh,
    'telegramAuth': telegramAuth,
    'greeting': greeting,
    'workoutHistory': workoutHistory,
    'trainingSchedule': trainingSchedule,
  };

  @override
  Map<String, _i2.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_core': modules.serverpod_auth_core,
    'serverpod_auth_idp': modules.serverpod_auth_idp,
  };
}
